Loading Numpy

In [163]:
import numpy as np

In [164]:
a = np.array([45,7,8], dtype='int16')# change int type to occupy minimal space. Will change itemsize

In [165]:
for num in a:
    print(num)

45
7
8


In [166]:
b = np.array([[45,7,8],[89,56,74]])

print(b[0][1])

7


In [167]:
#Get dimensions
b.ndim
#Get shape
b.shape
#get Datatype
a.dtype

dtype('int16')

In [168]:
#get size
a.itemsize

2

In [169]:
#Get total size
a.size * a.itemsize
#a.nbytes

6

Altering Specific Elements in Rows and Columns

In [170]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [171]:
#get number of rows and columns
d.shape

(2, 7)

In [172]:
#Get specific element [r, c]
d[1][-6]

9

In [173]:
print(d[0])

[1 2 3 4 5 6 7]


In [174]:
#Getting [start:end:step]
d[0, 1:6:2]

array([2, 4, 6])

In [175]:
d[:,2] = [45,78] #In all the rows, in the third column change the values to 45 and 78 respectively
print(d)

[[ 1  2 45  4  5  6  7]
 [ 8  9 78 11 12 13 14]]


initializing Different Types of Arrays

In [176]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [177]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [178]:
np.full((2,3), 68)

array([[68, 68, 68],
       [68, 68, 68]])

In [179]:
#Random integer Values
np.random.randint(6, size=(4,3))

array([[2, 2, 3],
       [3, 4, 2],
       [0, 3, 1],
       [5, 4, 3]])

In [180]:
#Random decimal Values
np.random.rand(6,3)

array([[0.39788414, 0.60788446, 0.10779242],
       [0.88432192, 0.54290458, 0.18564727],
       [0.24342404, 0.50670719, 0.24340894],
       [0.19248657, 0.54745456, 0.80301108],
       [0.25828815, 0.62721827, 0.98632399],
       [0.79924831, 0.31665392, 0.41089082]])

In [181]:
#identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [182]:
#repeat an array
arr = np.array([[45,90,83]])
rep = np.repeat(arr, 3, axis=0)
print(rep)

[[45 90 83]
 [45 90 83]
 [45 90 83]]


In [183]:
#draw a matrix box
box = np.ones((5,5)) 
box[1:-1,1:-1] = 0 #setting Rows and Columns to Zero #mark the end point
box[2,2] = 9
print(box)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Linear Algebra

In [184]:
a = np.ones((2,3))
b = np.full((3,2),3)

print(a)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]


array([[9., 9.],
       [9., 9.]])

In [185]:
c = np.identity(3)
#to get the determinant of the above identity matrix
np.linalg.det(c)

1.0

Statistics

In [186]:
stats = np.array([[1,2,3],[8,7,6]])
# find minimum value
np.min(stats)

1

In [187]:
# on row basis
np.max(stats, axis=1)

array([3, 8])

In [188]:
# Summing up all of the elements
np.sum(stats)

27

In [189]:
np.sum(stats, axis=1) #find sum across
np.sum(stats, axis=0)

array([9, 9, 9])

In [190]:
filedata = np.genfromtxt('array_data.txt', delimiter=',')
# Changing format to int
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Boolean Masking and Advanced Indexing

In [191]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [192]:
#Picking actual values greater than 50
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])